---
.travis.yml:
  secure: "Ojc0h2mbt9Y+eCyiKD+x1iYNONOP27Me63hjo9jo2v1bSs3aiM7djlcpz/sG+jRJ7JQoUyaGzHSn+gvxwWqdagFfFgDmipMKD0OXQinq7upRaG2hR+akKo0jllq9zLjJGBDoxurioKfOzPGlt2bX3UYY5KyeJ3AIM4dwCGVtSh4="
  docker_sets:
    - set: debian8-64
    - set: debian9-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
    - set: centos6-64
    - set: centos7-64
appveyor.yml:
  delete: true
spec/spec_helper.rb:
  allow_deprecations: true
  spec_overrides: "require 'spec_helper_local'"
  mock_with: ':mocha'
